[package]
name = "r-iva9/antera"
description = "Reactive UI Framework for Luau and the Allure Ecosystem."
license = "MIT"
authors = ["r-iva9"]
version = "1.0.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
